import { Component, OnInit } from '@angular/core';
import { RequestrService } from 'src/app/services/requestr.service';
import { HttpResponse } from '@angular/common/http';

const urls = {
  books: 'https://anapioficeandfire.com/api/books',
};

// Generated by https://quicktype.io

export interface Character {
  url: string;
  name: string;
  gender: string;
  culture: string;
  born: string;
  died: string;
  titles: string[];
  aliases: string[];
  father: string;
  mother: string;
  spouse: string;
  allegiances: string[];
  books: string[];
  povBooks: any[];
  tvSeries: string[];
  playedBy: string[];
}

export interface Book {
  url: string;
  name: string;
  isbn: string;
  authors: string[];
  numberOfPages: number;
  publisher: string;
  country: string;
  mediaType: string;
  released: string;
  characters: string[];
  povCharacters: string[];
  characterPage?: number;
  characterDatas: Character[];
}

@Component({
  selector: 'app-books',
  templateUrl: './books.component.html',
  styleUrls: ['./books.component.scss'],
})
export class BooksComponent implements OnInit {
  readonly CHARACTER_PAGE_SIZE = 12;
  books: Book[];
  pageNumber = 1;
  pageNumbers = [1, 2];
  bookTitleUrlMap: { [key: string]: Book } = {};
  constructor(private requestr: RequestrService) {}

  ngOnInit() {
    this.fetchBooks(this.pageNumber);
  }

  async fetchBooks(page: number, pageSize = 10) {
    this.pageNumber = page;
    try {
      const res: HttpResponse<Book[]> = await this.requestr.get(
        urls.books,
        null,
        {
          page,
          pageSize,
        }
      );
      this.books = this.initializeBookData(res.body);
      this.books.forEach((b) => this.fetchCharacters(b));
    } catch (e) {
      alert('Error Occured when fetching books');
    }
  }

  async fetchCharacters(book: Book) {
    const page = book.characterPage;
    const start = page * this.CHARACTER_PAGE_SIZE;
    const end = (page + 1) * this.CHARACTER_PAGE_SIZE;

    const res = await Promise.all(
      book.characters.slice(start, end).map((c) => this.requestr.get(c))
    );
    const characters: Character[] = res.map((r) => r.body);

    if (!book.characterDatas) {
      book.characterDatas = characters;
    } else {
      book.characterDatas = [...book.characterDatas, ...characters];
    }
    characters.forEach((c) => this.fetchAllMentionedBooks(c.books));
    book.characterPage = page + 1;
  }

  async addTitleToMap(book: Book) {
    this.bookTitleUrlMap[book.url] = book;
  }

  async fetchAllMentionedBooks(books: string[]) {
    const filteredBooks = books.filter(
      (b) => !Object.keys(this.bookTitleUrlMap).includes(b)
    );
    const res = await Promise.all(
      filteredBooks.map((fb) => this.requestr.get(fb))
    );
    const fetchedBooks: Book[] = res.map((r) => r.body);
    fetchedBooks.forEach((fb) => this.addTitleToMap(fb));
  }

  async requestTitleFromServer(url: string) {}

  private initializeBookData(books: Book[]) {
    return books.map((b) => {
      this.addTitleToMap(b);
      return { ...b, characterPage: 0 };
    });
  }
}
